# Generated by Django 5.2.3 on 2025-07-01 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Asiento contable',
                'verbose_name_plural': 'Asientos contables',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Cuentas contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='asientos_contables.asientocontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asientos_contables.cuentacontable')),
            ],
            options={
                'verbose_name': 'Movimiento contable',
                'verbose_name_plural': 'Movimientos contables',
            },
        ),
    ]
