# Generated by Django 5.2.3 on 2025-07-02 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asientos_contables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asientocontable",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 7, 2, 2, 14, 48, 892306, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Fecha de creación",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asientocontable",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AddField(
            model_name="cuentacontable",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 7, 2, 2, 14, 57, 383177, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Fecha de creación",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cuentacontable",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de actualización"
            ),
        ),
        migrations.AlterField(
            model_name="cuentacontable",
            name="codigo",
            field=models.CharField(
                error_messages={
                    "unique": "Ya existe una cuenta contable con este código."
                },
                max_length=20,
                unique=True,
            ),
        ),
    ]
