services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-contabilidad_db}
      POSTGRES_USER: ${DB_USER:-contabilidad_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-contabilidad_pass}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-contabilidad_user} -d ${DB_NAME:-contabilidad_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
