services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DEBUG=1

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: contabilidad_db
      POSTGRES_USER: contabilidad_user
      POSTGRES_PASSWORD: contabilidad_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contabilidad_user -d contabilidad_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
